exclude:
  - readme.md
  - .github/
header_pages:
  - index.html
author: Amrit Pratihar
github_username:  Amrit-Hub
plugins:
  - jekyll-sitemap
  - jekyll-mentions
  - jemoji
markdown: kramdown
kramdown:
   syntax_highlighter_opts:
      disable : true
